[pytest]
pythonpath = .
asyncio_mode = auto
filterwarnings =
    ignore:.*gotrue.*deprecated.*:DeprecationWarning
    ignore:'crypt' is deprecated and slated for removal in Python 3\.13:DeprecationWarning:passlib\.utils\.__init__
testpaths = tests
python_files = test_*.py
