[pytest]
python_paths = .
testpaths = tests
python_files = test_*.py
addopts = -v --strict-markers
pythonpath = . app
env =
    PYTHONPATH=.
    TESTING=true
    CELERY_ALWAYS_EAGER=true
markers =
    unit: Unit tests
    integration: Integration tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
