from app.routers import (
    ai,
    handwriting_simple as handwriting,
    assignments,
    courses,
    auth,
    hybrid,
    student,
    personalization,
    community,
    admin,
    pathway,
    teacher,
    knowledge_graph,
    generation,
    parent,
    mentor,
    peer_tutor,
    counselor,
    content_creator,
    researcher,
    alumni,
    curriculum,
)
