from . import (
    ai,
    ai_governance,
    ai_agents,
    analytics,
    assessment,
    assignments,
    attendance,
    auth,
    community,
    courses,
    curriculum,
    departments,
    enrollments,
    faculties,
    generation,
    handwriting_simple as handwriting,
    hybrid,
    institutions,
    knowledge_graph,
    onboarding,
    pathway,
    personalization,
    realtime,
    schedule,
    users,
    # Role-specific legacy (to be consolidated)
    admin,
    student,
    teacher,
    parent,
    mentor,
    peer_tutor,
    counselor,
    content_creator,
    researcher,
    alumni,
)
