from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import os
import json
import google.generativeai as genai
import structlog
from datetime import datetime
import time

from ai_engine.llm import get_llm_provider
from ai_engine.rag import get_rag_engine
from ai_engine.prompts import A2UI_SYSTEM_PROMPT
from ai_engine.skills import get_skill_manager
from app.services.ppt_generator import PPTGenerator
from app.services.personalization_service import get_personalization_service
from app.personalization.schemas import LearningEventType
from app.core.metrics import AI_REQUESTS, AI_LATENCY
from app.core.audit import audit_logger
from ai_engine.swarm.pathway import PathwayAgent
from learner_profile.models.behavior import BehaviorModel

# Initialize router and logger
router = APIRouter()
logger = structlog.get_logger()


class CourseGenerationRequest(BaseModel):
    topic: str
    level: str = "Beginning"
    modules: int = 4


class IngestRequest(BaseModel):
    text: str
    metadata: Optional[Dict[str, Any]] = None


class AssignmentCourseRequest(BaseModel):
    """Generate a course personalized to an assignment and optional submission.

    Uses the assignment description and the learner's score (if provided)
    to set difficulty and focus areas.
    """

    assignment_id: str
    submission_id: Optional[str] = None
    modules: int = 4


class CourseGenerationResponse(BaseModel):
    title: str
    description: str
    outline: List[str]


class TutorChatRequest(BaseModel):
    message: str
    user_id: str = "guest"
    session_id: Optional[str] = "default-session"
    context_filters: Optional[dict] = None
    provider: str = "auto"


class TutorChatResponse(BaseModel):
    response: str
    content: Optional[str] = None
    context_used: List[str]
    personalization: Dict[str, Any]


# ... (IngestRequest remains same)

# Note: We need to instantiate LLM per request to support dynamic provider switching,
# or use the factory inside the route.
# The global 'llm' variable at line 10 is static. We should stop using it for dynamic requests.


@router.post("/generate-course", response_model=CourseGenerationResponse)
async def generate_course(request: CourseGenerationRequest):
    """
    Generate a course outline using local Ollama instance (default) or specified provider.
    """
    # For course generation, we default to auto (likely gemini if key exists)
    llm_instance = get_llm_provider("auto")

    system_prompt = "You are an expert curriculum designer. Create a structured course outline."
    user_prompt = f"""
    Create a {request.level} level course about "{request.topic}".
    The course should have exactly {request.modules} modules.

    Return the response in strictly valid JSON format with the following structure:
    {{
        "title": "Course Title",
        "description": "Brief summary of the course",
        "outline": [
            "Module 1: Title - Brief Description",
            "Module 2: Title - Brief Description",
            ...
        ]
    }}
    Do not include any explanation, only the JSON.
    """

    start_time = time.time()
    try:
        raw_response = await llm_instance.agenerate(user_prompt, system_prompt)
        AI_LATENCY.labels(provider="auto", model="course_gen").observe(time.time() - start_time)
        AI_REQUESTS.labels(provider="auto", model="course_gen", status="success").inc()

        # Simple cleanup
        clean_response = raw_response.replace("```json", "").replace("```", "").strip()
        import json

        data = json.loads(clean_response)

        audit_logger.log(
            action="course_generated",
            user_id="ai_system",  # Or request.user_id if available
            resource_id=data.get("title"),
            metadata={"topic": request.topic, "level": request.level},
        )

        return CourseGenerationResponse(
            title=data.get("title", f"Course on {request.topic}"),
            description=data.get("description", "Generated by AI"),
            outline=data.get("outline", []),
        )
    except Exception as e:
        AI_REQUESTS.labels(provider="auto", model="course_gen", status="error").inc()
        logger.error("course_generation_failed", topic=request.topic, error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/generate-course-from-assignment", response_model=CourseGenerationResponse)
async def generate_course_from_assignment(request: AssignmentCourseRequest):
    """Generate a course outline based on an assignment and optional submission.

    - If submission_id is provided and graded, uses the score to set level.
    - Uses the assignment title/description as the topic/context.
    """
    from app.store.assignment_store import AssignmentStore

    # Instantiate LLM (Default auto)
    llm_instance = get_llm_provider("auto")

    store = AssignmentStore()
    assignment = await store.get_assignment(request.assignment_id)
    if not assignment:
        raise HTTPException(status_code=404, detail="Assignment not found")

    title = assignment.get("title", "AI-generated course")
    description = assignment.get("description", "")

    # Default level
    level_label = "Beginning"

    score = None
    if request.submission_id:
        submissions = await store.get_submissions(request.assignment_id)
        submission = next((s for s in submissions if s["id"] == request.submission_id), None)
        if submission and submission.get("grade") is not None:
            score = float(submission["grade"])

    if score is not None:
        # Simple mapping: 0–100 numeric grade
        if score < 40:
            level_label = "Remedial / Beginner"
        elif score < 70:
            level_label = "Intermediate"
        else:
            level_label = "Advanced / Enrichment"

    system_prompt = "You are an expert curriculum designer. Create a structured course outline tailored to a specific assignment and learner performance."
    user_prompt = f"""
    Assignment Title: {title}
    Assignment Description: {description}

    Learner Performance:
    - Score: {score if score is not None else 'N/A'}
    - Level: {level_label}

    Design a {request.modules}-module course that helps the learner master the skills needed for this assignment.
    Emphasize remediation where the score is low, and extension where the score is high.

    Return the response in strictly valid JSON format with the following structure:
    {{
        "title": "Course Title",
        "description": "Brief summary of the course",
        "outline": [
            "Module 1: Title - Brief Description",
            "Module 2: Title - Brief Description",
            ...
        ]
    }}
    Do not include any explanation, only the JSON.
    """

    try:
        raw_response = await llm_instance.agenerate(user_prompt, system_prompt)
        clean_response = raw_response.replace("```json", "").replace("```", "").strip()
        import json

        data = json.loads(clean_response)

        return CourseGenerationResponse(
            title=data.get("title", f"Course for {title}"),
            description=data.get("description", "Generated by AI"),
            outline=data.get("outline", []),
        )
    except Exception as e:
        logger.error(
            "assignment_course_generation_failed", assignment_id=request.assignment_id, error=str(e)
        )
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/tutor/chat", response_model=TutorChatResponse)
async def tutor_chat(request: TutorChatRequest):
    """
    Chat with the AI Tutor using the Orchestrator for multi-agent routing.
    Includes [NEW] Swarm Integration.
    """
    from ai_engine.swarm.orchestrator import Orchestrator
    
    try:
        # 1. Initialize Swarm and Learner Engine
        orchestrator = Orchestrator()
        personalization = get_personalization_service()
        
        # 2. Get Learner Profile for context
        profile = await personalization.get_legacy_state(request.user_id)

        # 3. Route via Orchestrator
        # Context for the agents
        context = {
            "user_id": request.user_id,
            "session_id": request.session_id,
            "history": [], # In production, fetch history from state
            "filters": request.context_filters,
            "topic": (request.context_filters or {}).get("topic", "General"),
        }
        
        # [NEW] The Swarm handles safety, intent classification, and RAG
        result = await orchestrator.route_request(request.message, context, learner_profile=profile)
        
        # If the result is a dict (likely A2UI), return as response
        if isinstance(result, dict):
            # Convert dict to string for the 'response' field if it's not already
            response_text = result.get("response") or json.dumps(result)
            personalization_payload = {
                "message": request.message,
                "response": response_text,
                "session_id": request.session_id,
                "behavior": profile.get("behavior_label", "neutral"),
                "recommendation": profile.get("risk_summary", {}).get("risk_level"),
                "topic": context.get("topic"),
            }
            await personalization.record_event(
                request.user_id,
                LearningEventType.TUTOR_INTERACTION,
                payload=personalization_payload,
                source="ai_router",
                topic_id=context.get("topic"),
                session_id=request.session_id,
            )
            return {
                "response": response_text,
                "content": response_text,
                "context_used": result.get("context_used", []),
                "personalization": {
                    "behavior": profile.get("behavior_label", "neutral"),
                    "cognitive_load": profile.get("cognitive_load", 50),
                    "mastery": profile.get("mastery_scores", {}),
                    "risk": profile.get("risk_summary", {}),
                },
            }
        
        # Fallback for string responses
        await personalization.record_event(
            request.user_id,
            LearningEventType.TUTOR_INTERACTION,
            payload={
                "message": request.message,
                "response": str(result),
                "session_id": request.session_id,
                "behavior": profile.get("behavior_label", "neutral"),
                "topic": context.get("topic"),
            },
            source="ai_router",
            topic_id=context.get("topic"),
            session_id=request.session_id,
        )
        return {
            "response": str(result),
            "content": str(result),
            "context_used": [],
            "personalization": {
                "behavior": profile.get("behavior_label", "neutral"),
                "risk": profile.get("risk_summary", {}),
            },
        }

    except Exception as e:
        AI_REQUESTS.labels(provider=request.provider, model="tutor_chat", status="error").inc()
        logger.error("tutor_chat_swarm_failed", user_id=request.user_id, error=str(e))
        raise HTTPException(status_code=500, detail=str(e))

    except Exception as e:
        AI_REQUESTS.labels(provider=request.provider, model="tutor_chat", status="error").inc()
        logger.error("tutor_chat_failed", user_id=request.user_id, error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/tutor/ingest")
async def ingest_content(request: IngestRequest):
    """
    Ingest text content into the RAG vector store.
    """
    try:
        rag_engine = get_rag_engine()
        rag_engine.ingest_text(request.text, request.metadata)
        return {"status": "success", "message": "Content ingested successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# --- Pathway Agent Integration ---

_pathway_agent = None
_behavior_model = None


def get_pathway_agent():
    global _pathway_agent
    if _pathway_agent is None:
        _pathway_agent = PathwayAgent()
    return _pathway_agent


def get_behavior_model():
    global _behavior_model
    if _behavior_model is None:
        _behavior_model = BehaviorModel()
    return _behavior_model


class PathwayRequest(BaseModel):
    learner_state: dict
    curriculum_graph: dict


class BehaviorRequest(BaseModel):
    session_data: dict


@router.post("/pathway/recommend")
async def recommend_pathway(request: PathwayRequest):
    """
    Get next node recommendation from Pathway Agent.
    """
    recommendation = get_pathway_agent().recommend_next_node(
        request.learner_state, request.curriculum_graph
    )
    return {"recommendation": recommendation}


@router.post("/profile/behavior")
async def classify_behavior(request: BehaviorRequest):
    """
    Classify learner behavior.
    """
    model = get_behavior_model()
    label = model.classify_behavior(request.session_data)
    score = model.calculate_engagement_score(request.session_data)
    return {"behavior": label, "engagement_score": score}


# --- PowerPoint Generation ---


class PPTGenerationRequest(BaseModel):
    """Request model for PPT generation."""

    topic: str
    slides_count: int = 8
    user_id: str = "guest"


class PPTGenerationResponse(BaseModel):
    """Response model for PPT generation."""

    success: bool
    message: str
    download_url: Optional[str] = None
    filename: Optional[str] = None
    file_size: Optional[str] = None
    slide_count: Optional[int] = None
    slide_titles: Optional[List[str]] = None
    content_structure: Optional[Dict[str, Any]] = None


# Initialize Gemini API
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)


@router.post("/tutor/generate-ppt", response_model=PPTGenerationResponse)
async def generate_ppt(request: PPTGenerationRequest):
    """
    Generate a PowerPoint presentation on a given topic using Gemini API.

    Args:
        request: PPT generation request with topic and slide count

    Returns:
        PPTGenerationResponse with download URL and metadata
    """
    try:
        # [OPTIMIZATION] Step 0: Check Cache
        safe_topic_key = request.topic.lower().strip().replace(" ", "_")
        # Find if any file starts with this topic key and is recent (optional)
        # For now, simple strict caching: look for a cache map or just check existing files
        # We'll implement a simple JSON-based cache map for better tracking

        cache_file = "data/ppt_cache.json"
        os.makedirs("data", exist_ok=True)
        try:
            if os.path.exists(cache_file):
                with open(cache_file, "r") as f:
                    cache = json.load(f)
            else:
                cache = {}

            cache_key = f"{safe_topic_key}_{request.slides_count}"
            if cache_key in cache:
                cached_data = cache[cache_key]
                if os.path.exists(cached_data["filepath"]):
                    print(f"Serving cached PPT for {request.topic}")
                    return PPTGenerationResponse(**cached_data["response"])
        except Exception as e:
            logger.warning("ppt_cache_read_failed", topic=request.topic, error=str(e))
            cache = {}

        # Step 1: Generate content structure using Gemini API
        # Use GeminiRestProvider via get_llm_provider for Python 3.8 compatibility
        llm = get_llm_provider("gemini")

        # [OPTIMIZATION] Reduced verbosity in prompt to save output tokens and time
        prompt = f"""Topic: {request.topic}
Slides: {request.slides_count}

Generate a JSON structure for a PowerPoint presentation.
Format:
{{
  "title": "Main Title",
  "subtitle": "Subtitle",
  "slides": [
    {{ "title": "Slide 1", "bullets": ["A", "B", "C"] }}
  ]
}}
Strict JSON only."""

        # Generate content
        content_text = await llm.agenerate(prompt)
        content_text = content_text.strip()

        # Clean up response (remove markdown code blocks if present)
        if content_text.startswith("```json"):
            content_text = content_text.replace("```json", "").replace("```", "").strip()
        elif content_text.startswith("```"):
            content_text = content_text.replace("```", "").strip()

        # Parse JSON response
        try:
            content_structure = json.loads(content_text)
        except json.JSONDecodeError as e:
            logger.error("ppt_json_parse_failed", error=str(e), response_sample=content_text[:500])
            raise HTTPException(
                status_code=500, detail="Failed to parse AI response. Please try again."
            )

        # Step 2: Generate PowerPoint using PPTGenerator
        ppt_gen = PPTGenerator()
        filepath = ppt_gen.create_presentation(request.topic, content_structure)

        # Step 3: Get file metadata
        filename = os.path.basename(filepath)
        file_size = ppt_gen.get_file_size(filepath)
        slide_titles = [slide.get("title", "") for slide in content_structure.get("slides", [])]

        # Step 4: Create download URL
        download_url = f"/api/tutor/download-ppt/{filename}"

        response_data = {
            "success": True,
            "message": f"Presentation '{request.topic}' generated successfully!",
            "download_url": download_url,
            "filename": filename,
            "file_size": file_size,
            "slide_count": len(content_structure.get("slides", [])) + 1,  # +1 for title slide
            "slide_titles": slide_titles,
            "content_structure": content_structure,
        }

        # [OPTIMIZATION] Save to Cache
        try:
            cache_key = f"{safe_topic_key}_{request.slides_count}"
            cache[cache_key] = {
                "filepath": filepath,
                "response": response_data,
                "timestamp": datetime.now().isoformat(),
            }
            with open(cache_file, "w") as f:
                json.dump(cache, f)
        except Exception as e:
            print(f"Cache Write Error: {e}")

        return PPTGenerationResponse(**response_data)

    except Exception as e:
        logger.error("ppt_generation_failed", topic=request.topic, error=str(e))
        raise HTTPException(status_code=500, detail=f"Failed to generate presentation: {str(e)}")


@router.get("/tutor/download-ppt/{filename}")
async def download_ppt(filename: str):
    """
    Download a generated PowerPoint file.

    Args:
        filename: Name of the PPTX file to download

    Returns:
        FileResponse with the PPTX file
    """
    filepath = os.path.join("static/presentations", filename)

    if not os.path.exists(filepath):
        raise HTTPException(status_code=404, detail="File not found")

    return FileResponse(
        path=filepath,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        filename=filename,
    )
