import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { z } from 'zod';

const sendMessageSchema = z.object({
    message: z.string().min(1),
    agentId: z.string().optional(),
    projectId: z.string().optional(),
});

// POST /api/chat/send - Send a chat message
export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const validation = sendMessageSchema.safeParse(body);

        if (!validation.success) {
            return NextResponse.json(
                { error: 'Invalid input', details: validation.error.errors },
                { status: 400 }
            );
        }

        const { message, agentId, projectId } = validation.data;

        // TODO: Get userId from auth middleware
        const userId = 'demo-user-id'; // Placeholder

        // Store user message
        const chatLog = await prisma.chatLog.create({
            data: {
                userId,
                agentId,
                projectId,
                message,
                role: 'USER',
            },
        });

        // If agent specified, create a response (in production, this would trigger agent processing)
        if (agentId) {
            const agent = await prisma.agent.findUnique({
                where: { id: agentId },
            });

            if (agent) {
                const agentResponse = await prisma.chatLog.create({
                    data: {
                        userId,
                        agentId,
                        projectId,
                        message: `This is a demo response from ${agent.name}. In production, this would be generated by the AI agent.`,
                        role: 'AGENT',
                    },
                });

                return NextResponse.json({
                    userMessage: chatLog,
                    agentResponse,
                });
            }
        }

        return NextResponse.json({ message: chatLog });
    } catch (error) {
        console.error('Send message error:', error);
        return NextResponse.json(
            { error: 'Internal server error' },
            { status: 500 }
        );
    }
}
