import asyncio
import uuid
import sys
import os
from datetime import datetime

# Setup path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "backend")))
from app.main import app
from app.store.user_store import UserStore
from app.store.content_store import ContentStore
from app.store.course_store import CourseStore
from httpx import AsyncClient, ASGITransport

async def verify_v2():
    async with AsyncClient(base_url="http://localhost:8000") as ac:
        user_store = UserStore()
        content_store = ContentStore()
        course_store = CourseStore()

        print("--- 1. Setup Mock User ---")
        email = f"teacher_{uuid.uuid4().hex[:6]}@example.com"
        pwd = "password123"
        name = "V2 Teacher"
        phone = f"+1555{uuid.uuid4().int % 1000000:06d}"
        user = await user_store.create_user(email, pwd, name, "teacher", phone)
        print(f"Created teacher: {user['id']}")

        student_email = f"student_{uuid.uuid4().hex[:6]}@example.com"
        student = await user_store.create_user(student_email, pwd, "V2 Student", "student", phone)
        print(f"Created student: {student['id']}")

        # Get Token
        token_res = await ac.post("/api/auth/token", data={"username": email, "password": pwd})
        if token_res.status_code != 200:
            print(f"Token error {token_res.status_code}: {token_res.text}")
            return
        token = token_res.json()["access_token"]
        headers = {"Authorization": f"Bearer {token}"}

        print("\n--- 2. Test Content Pipeline ---")
        # Log Upload
        upload_data = {
            "original_filename": "syllabus.pdf",
            "storage_url": "https://example.com/syllabus.pdf",
            "file_type": "pdf",
            "file_size_bytes": 1024
        }
        upload_res = await ac.post("/api/teacher/content/upload", params=upload_data, headers=headers)
        upload = upload_res.json()
        print(f"Logged upload: {upload['id']}")

        # Mock a scaffold being generated by AI (manual DB update for test)
        scaffold = {
            "title": "Quantum Physics 101",
            "code": f"QP101_{uuid.uuid4().hex[:4]}",
            "description": "Intro to quantum",
            "modules": [{"title": "Introduction", "lessons": [{"title": "Wave-Particle Duality"}]}]
        }
        await content_store.update_content_upload(upload["id"], {"scaffold_json": scaffold})
        print("Mocked scaffold in DB.")

        # Get Scaffold
        scaffold_res = await ac.get(f"/api/teacher/content/scaffold/{upload['id']}", headers=headers)
        print(f"Retrieved scaffold: {scaffold_res.json()['title']}")

        # Approve Scaffold
        approve_res = await ac.post(f"/api/teacher/content/scaffold/approve/{upload['id']}", headers=headers)
        course = approve_res.json()
        print(f"Approved scaffold, created course: {course['id']}")

        print("\n--- 3. Test AI Verification Queue ---")
        # Create queue item
        await content_store.create_verification_item(
            student_id=str(student["id"]),
            teacher_id=str(user["id"]),
            student_question="What is entanglement?",
            ai_generated_answer="It is a quantum phenomenon."
        )
        print("Created verification item.")

        # Get Queue
        queue_res = await ac.get("/api/teacher/verification/queue", headers=headers)
        queue = queue_res.json()
        print(f"Queue size: {len(queue)}")

        # Edit and Approve
        item_id = queue[0]["id"]
        update_res = await ac.patch(
            f"/api/teacher/verification/queue/{item_id}",
            params={"status": "edited", "teacher_edited_answer": "It is a phenomenon where particles share state."},
            headers=headers
        )
        print(f"Updated item: {update_res.json()['status']}")

        print("\n--- 4. Cleanup ---")
        await user_store.delete_user(user["id"])
        print("Deleted teacher user.")
        print("\n✅ V2 Features Verified Successfully!")

if __name__ == "__main__":
    asyncio.run(verify_v2())
