"""
Lumina Automation — Final Report Generator
"""

from datetime import datetime
from pathlib import Path
from automation.config import REPORT_FILE
from automation.logger import log, ok, fail, section


def _status(value) -> str:
    if value is True or value == "approved" or value == "completed":
        return "✅ PASS"
    if value is False or value is None:
        return "❌ FAIL"
    if isinstance(value, int) and value > 0:
        return f"✅ {value}"
    if isinstance(value, str):
        return f"ℹ️  {value}"
    return f"ℹ️  {value}"


def generate_report(results: dict) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Tally pass / fail
    checks = {
        "Backend Health":         results.get("backend_up"),
        "Frontend Health":        results.get("frontend_up"),
        "DB Seeding":             results.get("seeded"),
        "Admin Login":            bool(results.get("tokens", {}).get("admin")),
        "HOD Login":              bool(results.get("tokens", {}).get("hod")),
        "Teacher Login":          bool(results.get("tokens", {}).get("teacher")),
        "Student Login":          bool(results.get("tokens", {}).get("student")),
        "College Created":        bool(results.get("academic", {}).get("college_id")),
        "Department Created":     bool(results.get("academic", {}).get("dept_id")),
        "Batch Created":          bool(results.get("academic", {}).get("batch_id")),
        "Enrollment Code":        bool(results.get("academic", {}).get("enrollment_code")),
        "Course Created":         bool(results.get("teacher", {}).get("course_id")),
        "Assignment Created":     bool(results.get("teacher", {}).get("assignment_id")),
        "Student Enrolled":       bool(results.get("student", {}).get("enrolled_student")),
        "Assignment Submitted":   results.get("student", {}).get("assignment_submitted"),
        "AI Question Asked":      bool(results.get("ai", {}).get("question_id")),
        "AI Queue Approved":      results.get("ai", {}).get("approved"),
        "AI Tutor Chat":          results.get("ai", {}).get("ai_tutor_chat"),
        "Faculty Dashboard":      results.get("faculty", {}).get("faculty_dashboard"),
        "HOD Dashboard":          results.get("faculty", {}).get("hod_dashboard"),
        "Assignment Graded":      results.get("faculty", {}).get("graded"),
    }

    passed = sum(1 for v in checks.values() if v is True)
    total  = len(checks)
    score  = int(passed / total * 100)

    if passed == total:
        verdict = "🚀 DEMO-READY"
    elif passed >= total * 0.75:
        verdict = "⚠️  MOSTLY READY (minor gaps)"
    else:
        verdict = "❌ NOT READY — fix failures above"

    # Build markdown
    lines = [
        f"# Lumina Automation Report",
        f"",
        f"**Date:** {ts}  ",
        f"**Score:** {passed}/{total} checks passed ({score}%)  ",
        f"**Verdict:** {verdict}",
        f"",
        f"## Check Results",
        f"",
        f"| Check | Status |",
        f"|-------|--------|",
    ]
    for name, val in checks.items():
        lines.append(f"| {name} | {_status(val)} |")

    lines += [
        f"",
        f"## Context IDs",
        f"",
        f"| Resource | ID |",
        f"|----------|----|",
        f"| College   | {results.get('academic', {}).get('college_id', '—')} |",
        f"| Department | {results.get('academic', {}).get('dept_id', '—')} |",
        f"| Batch      | {results.get('academic', {}).get('batch_id', '—')} |",
        f"| Subject    | {results.get('academic', {}).get('subject_id', '—')} |",
        f"| Course     | {results.get('teacher', {}).get('course_id', '—')} |",
        f"| Assignment | {results.get('teacher', {}).get('assignment_id', '—')} |",
        f"",
        f"## Demo Credentials",
        f"",
        f"| Role | Email | Password |",
        f"|------|-------|----------|",
        f"| Super Admin | admin@lumina.com | Lumina@138800 |",
        f"| HOD         | hod@lumina.com   | Lumina@138800 |",
        f"| Teacher     | teacher@lumina.com | Lumina@138800 |",
        f"| Student     | student@lumina.com | Lumina@138800 |",
        f"",
        f"## URLs",
        f"",
        f"- **Backend API:** http://localhost:8000",
        f"- **API Docs:**    http://localhost:8000/docs",
        f"- **Frontend:**    http://localhost:3000",
        f"",
        f"---",
        f"*Generated by Lumina One-Command Automation System*",
    ]

    report = "\n".join(lines)
    Path(REPORT_FILE).write_text(report, encoding="utf-8")
    return report


def print_summary(results: dict):
    section("FINAL AUTOMATION REPORT")
    report = generate_report(results)

    # Print condensed console summary
    checks_pass = sum(1 for k, v in {
        "backend":    results.get("backend_up"),
        "seed":       results.get("seeded"),
        "auth":       any(results.get("tokens", {}).values()),
        "academic":   bool(results.get("academic", {}).get("dept_id")),
        "teacher":    bool(results.get("teacher", {}).get("course_id")),
        "student":    bool(results.get("student", {})),
        "ai":         results.get("ai", {}).get("ai_tutor_chat"),
        "faculty":    results.get("faculty", {}).get("faculty_dashboard"),
    }.items() if v)

    total = 8
    log(f"Passed {checks_pass}/{total} phases")
    log(f"Report saved → {REPORT_FILE}")

    if checks_pass == total:
        ok("LUMINA IS FULLY DEMO-READY ✓")
    else:
        fail(f"Some phases need attention — see {REPORT_FILE} for details")
